from anthropic import Anthropic
from backend.services.llm.base import LLMService

class ClaudeService(LLMService):
    """LLM service implementation for Anthropic's Claude API."""

    def __init__(self, api_key: str):
        """Initialize the Anthropic client with the provided API key."""
        try:
            self.client = Anthropic(api_key=api_key)
        except Exception as e:
            raise ValueError(f"Failed to initialize Anthropic client: {str(e)}")

    def generate_response(self, model: str, prompt: str) -> str:
        """Generate a response from the Anthropic API based on the given prompt."""
        response = self.client.messages.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=4096,
            temperature=1.0,
        )

        thinking = ""

        for block in response.content:
            if block.type == "text":
                return block.text.strip()
            if block.type == "thinking":
                thinking += block.thinking
            
        raise ValueError("No text response generated by Anthropic API. Thinking content: " + thinking)

    def fetch_models(self) -> list[str]:
        """Fetch a list of available models from the Anthropic API."""
        try:
            data = self.client.models.list().data

            models = []
            for model in data:
                if model.type == "model":
                    models.append(model.id)
            return models
        except Exception as e:
            raise ValueError(f"Failed to fetch models from Anthropic API: {str(e)}")
