from google import genai
from backend.services.llm.base import LLMService

class GeminiService(LLMService):
    """LLM service implementation for Google's Gemini API."""

    def __init__(self, api_key: str):
        """Initialize the Gemini client with the provided API key."""
        try:
            self.client = genai.Client(api_key=api_key)
        except Exception as e:
            raise ValueError(f"Failed to initialize Gemini client: {str(e)}")

    def generate_response(self, model: str, prompt: str) -> str:
        """Generate a response from the Gemini API based on the given prompt."""
        response = self.client.models.generate_content(
            model=model,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
            }
        )

        if not response or not response.text:
            raise ValueError("No response generated by Gemini API.")

        return response.text.strip()

    def fetch_models(self) -> list[str]:
        """Fetch a list of available models from the Gemini API."""
        try:
            model_names = []

            for m in self.client.models.list():
                if not m.supported_actions:
                    continue
                for action in m.supported_actions:
                    if action == "generateContent":
                        model_names.append(m.name)

            return model_names
        except Exception as e:
            raise ValueError(f"Failed to fetch models from Gemini API: {str(e)}")
