from openai import OpenAI
from backend.services.llm.base import LLMService

class OpenAIService(LLMService):
    """LLM service implementation for OpenAI's API."""

    def __init__(self, api_key: str):
        """Initialize the OpenAI client with the provided API key."""
        try:
            self.client = OpenAI(api_key=api_key)
        except Exception as e:
            raise ValueError(f"Failed to initialize OpenAI client: {str(e)}")

    def generate_response(self, model: str, prompt: str) -> str:
        """Generate a response from the OpenAI API based on the given prompt."""
        response = self.client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=4096,
            temperature=0.7,
        )

        if not response.choices or not response.choices[0].message.content:
            raise ValueError("No response generated by OpenAI API.")

        return response.choices[0].message.content.strip()

    def fetch_models(self) -> list[str]:
        """Fetch a list of available models from the OpenAI API."""
        try:
            models = self.client.models.list()
            return [model.id for model in models.data]
        except Exception as e:
            raise ValueError(f"Failed to fetch models from OpenAI API: {str(e)}")
